# Generated by Django 5.1.3 on 2025-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
