# Generated by Django 5.1.3 on 2025-01-24 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bitacora', '0002_entrada_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coleccion', models.CharField(max_length=80)),
                ('detalle_coleccion', models.CharField(max_length=400)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='colecciones',
            field=models.ManyToManyField(blank=True, related_name='entradas', to='app_bitacora.coleccion'),
        ),
    ]
